version: '3.3'
services:
  web:
    build: .
    ports:
      - '13000:13000'
    env_file: .env
    volumes:
      - .:/usr/src/app
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:latest
  redis:
    image: redis:latest
